#!/usr/bin/env python3
"""groenmaker.

Usage:
    groenmaker compare <try_push> <central_push>
    groenmaker run -c <commit_hash> -q <fuzzy_query> [--leading-quote] [--fix]

Options:
    -h --help           Show this screen.
    -v --version        Show the groenmaker version.
    -q --query          Specify a fuzzy query for the mach tool
    -l --leading-quote  Add a leading single-quote to the mach fuzzy query
    -c --commit         Specify a Mercurial commit hash
    --fix               Run iteratively until all failing tests are disabled

"""
import os

from docopt import docopt

from pusher import pusher
from thdiff.thdiff import thdiff

# TODO REMOVE THIS CONSTANT
MC_REPO_PATH = "/home/bhyde/git/mozilla-central"


if __name__ == "__main__":
    try:
        args = docopt(__doc__, version="groenmaker 0.1.0")
        print(args)

        if args["compare"]:
            if all((args["<try_push>"], args["<central_push>"])):
                msg = f'Comparing try push {args["<try_push>"][:10]} '
                msg += f'with central push {args["<central_push>"][:10]}'
                print(msg)
                thdiff(args["<try_push>"], args["<central_push>"])
            else:
                err = "Error: please verify try and central commmits')"
                raise SystemExit(err)
        elif args["run"]:
            if args['--fix']:
                raise SystemExit('The --fix arg is not yet implemented 😔')
            commit_hash = args["<commit_hash>"]
            update_cmd = f"hg update -R {MC_REPO_PATH} {commit_hash}"
            print(f"Updating Mercurial repo to commit {commit_hash}")
            update = pusher.run(f"hg update -R {MC_REPO_PATH} {commit_hash}")
            if update[0] == 0:
                print(f"Successfully checked out {args['<commit_hash>']}")
                fuzz_q = args['<fuzzy_query>']
                os.chdir(MC_REPO_PATH)
                if args["--leading-quote"]:
                    push = "./mach try fuzzy --full -q "
                    push += '\\'
                    push += "'"
                    push += f"'{fuzz_q}'"
                else:
                    push = f"./mach try fuzzy --full -q '{fuzz_q}'"
                print('Running a try-push using the following mach command:')
                print(push)
                try_push = pusher.run(push)
                print(try_push[0], try_push[1], try_push[2], sep="\n\n")
    except KeyboardInterrupt:
        raise SystemExit("\nCTRL+C pressed. Exiting.\n")
